"""Initial migration

Revision ID: 7e0bc551bb32
Revises: 
Create Date: 2023-12-06 14:39:58.346758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0bc551bb32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('penulis', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.Column('gambar', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_persediaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perubahan_kuantitas', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_buku', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_buku'], ['buku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_persediaan')
    op.drop_table('buku')
    # ### end Alembic commands ###
